### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by sreekanthpulagam** [rakam-io/rakam#33]
```
2016-09-21T13:51:57.037Z        INFO    main    org.rakam.bootstrap.Bootstrap
2016-09-21T13:51:57.037Z        WARN    main    org.rakam.bootstrap.Bootstrap   UNUSED PROPERTIES
2016-09-21T13:51:57.037Z        WARN    main    org.rakam.bootstrap.Bootstrap   plugin.user.storage.identifier_column=id
2016-09-21T13:51:57.037Z        WARN    main    org.rakam.bootstrap.Bootstrap
2016-09-21T13:51:57.878Z        ERROR   main    org.rakam.bootstrap.Bootstrap   Uncaught exception in thread main
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'plugin.user.storage.identifier_column=id' was not used
  at org.rakam.bootstrap.Bootstrap.lambda$initialize$6(Bootstrap.java:198)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at org.rakam.bootstrap.Bootstrap.initialize(Bootstrap.java:212)
        at org.rakam.ServiceStarter.main(ServiceStarter.java:85)

```

**Comment by buremba** [comment]
Today, we `plugin.user.storage.identifier_column` renamed to `plugin.user.storage.identifier-column` but it seems that the Dockerfile still uses `identifier_column`. I fixed it and pushed the commit in master branch. Docker Hub should be updated in ~15 minutes.

**Comment by sreekanthpulagam** [comment]
@buremba working now
