### ISSUE TITLE
Exception in /user/get

### ISSUE THREAD

**Issue by fignuts** [rakam-io/rakam#46]
Related to https://github.com/rakam-io/rakam-ui/issues/38

Running latest Rakam from git as of 3/3

Stack trace

```
2017-03-03T21:49:00.575333+00:00 app[web.1]: java.lang.NullPointerException
2017-03-03T21:49:00.575333+00:00 app[web.1]: 	at org.rakam.postgresql.plugin.user.AbstractPostgresqlUserStorage.setValues(AbstractPostgresqlUserStorage.java:649)
2017-03-03T21:49:00.575334+00:00 app[web.1]: 	at org.rakam.postgresql.plugin.user.AbstractPostgresqlUserStorage.lambda$getUser$10(AbstractPostgresqlUserStorage.java:613)
2017-03-03T21:49:00.575337+00:00 app[web.1]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
2017-03-03T21:49:00.575338+00:00 app[web.1]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
2017-03-03T21:49:00.575338+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2017-03-03T21:49:00.575339+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2017-03-03T21:49:00.575340+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2017-03-03T21:49:00.575340+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by buremba** [comment]
Fixed, sorry for the bug. Currently the unit tests for user module are missing so it's hard to catch bugs.
