### ISSUE TITLE
Exception when clicking "save segment" in the people section of the UI

### ISSUE THREAD

**Issue by fignuts** [rakam-io/rakam#47]
Using postgresql deployment type, latest git version from 3/4

Stack trace:
```
2017-03-04T19:10:09.713725+00:00 app[web.1]: com.facebook.presto.sql.parser.ParsingException: line 1:66: no viable alternative at input '<EOF>'
2017-03-04T19:10:09.713726+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
2017-03-04T19:10:09.713727+00:00 app[web.1]: 	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
2017-03-04T19:10:09.713728+00:00 app[web.1]: 	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
2017-03-04T19:10:09.713729+00:00 app[web.1]: 	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
2017-03-04T19:10:09.713729+00:00 app[web.1]: 	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
2017-03-04T19:10:09.713730+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:5873)
2017-03-04T19:10:09.713731+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:5846)
2017-03-04T19:10:09.713731+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:3737)
2017-03-04T19:10:09.713732+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3458)
2017-03-04T19:10:09.713733+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3270)
2017-03-04T19:10:09.713734+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3126)
2017-03-04T19:10:09.713734+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2599)
2017-03-04T19:10:09.713735+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1273)
2017-03-04T19:10:09.713736+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:231)
2017-03-04T19:10:09.713736+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
2017-03-04T19:10:09.713737+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
2017-03-04T19:10:09.713738+00:00 app[web.1]: 	at org.rakam.plugin.MaterializedView.validateQuery(MaterializedView.java:50)
2017-03-04T19:10:09.713738+00:00 app[web.1]: 	at org.rakam.plugin.MaterializedView.<init>(MaterializedView.java:44)
2017-03-04T19:10:09.713739+00:00 app[web.1]: 	at org.rakam.postgresql.plugin.user.PostgresqlUserStorage.createSegment(PostgresqlUserStorage.java:125)
2017-03-04T19:10:09.713740+00:00 app[web.1]: 	at org.rakam.plugin.user.AbstractUserService.createSegment(AbstractUserService.java:58)
2017-03-04T19:10:09.713755+00:00 app[web.1]: 	at org.rakam.plugin.user.UserHttpService.createSegment(UserHttpService.java:227)
2017-03-04T19:10:09.713755+00:00 app[web.1]: 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
2017-03-04T19:10:09.713756+00:00 app[web.1]: 	at org.rakam.server.http.JsonParametrizedRequestHandler.handleInternal(JsonParametrizedRequestHandler.java:126)
2017-03-04T19:10:09.713756+00:00 app[web.1]: 	at org.rakam.server.http.JsonParametrizedRequestHandler.lambda$handle$1(JsonParametrizedRequestHandler.java:90)
2017-03-04T19:10:09.713757+00:00 app[web.1]: 	at org.rakam.server.http.RakamHttpRequest.handleBody(RakamHttpRequest.java:254)
2017-03-04T19:10:09.713757+00:00 app[web.1]: 	at org.rakam.server.http.HttpServerHandler.handleBody(HttpServerHandler.java:160)
2017-03-04T19:10:09.713758+00:00 app[web.1]: 	at org.rakam.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:112)
2017-03-04T19:10:09.713762+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
2017-03-04T19:10:09.713762+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
2017-03-04T19:10:09.713763+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
2017-03-04T19:10:09.713763+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
2017-03-04T19:10:09.713764+00:00 app[web.1]: 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
2017-03-04T19:10:09.713764+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
2017-03-04T19:10:09.713765+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
2017-03-04T19:10:09.713765+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
2017-03-04T19:10:09.713766+00:00 app[web.1]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
2017-03-04T19:10:09.713766+00:00 app[web.1]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
2017-03-04T19:10:09.713767+00:00 app[web.1]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
2017-03-04T19:10:09.713767+00:00 app[web.1]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2017-03-04T19:10:09.713768+00:00 app[web.1]: 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2017-03-04T19:10:09.713768+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)
2017-03-04T19:10:09.713769+00:00 app[web.1]: Caused by: org.antlr.v4.runtime.NoViableAltException
2017-03-04T19:10:09.713769+00:00 app[web.1]: 	at com.facebook.presto.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:5823)
2017-03-04T19:10:09.713770+00:00 app[web.1]: 	... 35 more
```

**Comment by buremba** [comment]
It looks like you filtered users by their attributes and there was a bug when no event filter is active. It fixed it and pushed to master.
